### ISSUE TITLE
Idle transformation calls

### ISSUE THREAD

**Issue by dohahamed** [Hundredl/MG-TSD#3]
Great ideas in the paper.

I am getting this error when I try any of the datasets:

Exception: Reached maximum number of idle transformation calls.
This means the transformation looped over 1 inputs without returning any output.
This occurred in the following transformation:
<gluonts.transform.split.InstanceSplitter object at 0x7f0f3c8a84c0>

**Comment by Hundredl** [comment]
Thank you for your question!

It seems like the issue might be related to the gluonts package. Could you provide more context to help us troubleshoot this? 
Specifically:
1. The version of the gluonts package you are using.
2. The structure or a sample of the dataset you are working with.
3. The code snippet you ran

This additional information will help us pinpoint the issue more accurately.

**Comment by dohahamed** [comment]
using the glutonts version you indicate in the source code resolved the issue. Thank you.
